[package]
name = "pimetrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.27.0"
rocket = "0.5.0-rc.1"
envy = "0.4"
serde = "1.0"